grant select on ACTIVITY_TYPE to cdc;

--drop table CDC_ACTIVITIES_10MIN_AGG_OK;
create table CDC_ACTIVITIES_10MIN_AGG_OK (
                                             ID NUMBER(18) GENERATED BY DEFAULT AS IDENTITY primary key
    ,GDATE date
    ,PDATE NUMBER(10)
    ,HOUR_MINUTE NUMBER(4)
    ,TYPE NUMBER(4)
    ,F_TYPE NUMBER(4)
    ,MINUTE_AMOUNT NUMBER(18)
    ,MINUTE_COUNT NUMBER(18)
    ,CREATIONDATE NUMBER(18)
);


select count(*) from CDC_ACTIVITIES_10MIN_AGG_OK
order by HOUR_MINUTE desc
;

-- truncate table CDC_ACTIVITIES_10MIN_AGG_OK;

create table ACTIVITY_TYPE_BL as
select * from mongodb.ACTIVITY_TYPE
;
alter table ACTIVITY_TYPE_BL add BL varchar2(50);

-- select 'update ACTIVITY_TYPE_BL set BL=''' || BL || ''' where DESCRIPTION='''|| DESCRIPTION ||''';' as u from ACTIVITY_TYPE_BL;
update ACTIVITY_TYPE_BL set BL='Payment' where DESCRIPTION='PURCHASE';
update ACTIVITY_TYPE_BL set BL='Payment' where DESCRIPTION='IN_APP_PURCHASE';
update ACTIVITY_TYPE_BL set BL='Payment' where DESCRIPTION='PORTAL_PURCHASE';
update ACTIVITY_TYPE_BL set BL='Payment' where DESCRIPTION='REFUND';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='REWARD';
update ACTIVITY_TYPE_BL set BL='Credit' where DESCRIPTION='CREDIT_PURCHASE';
update ACTIVITY_TYPE_BL set BL='Payment' where DESCRIPTION='PAYMENT_OFFLINE';
update ACTIVITY_TYPE_BL set BL='Payment' where DESCRIPTION='PAYMENT_REQUEST';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='PAYMENT_CARD(C2C)';
update ACTIVITY_TYPE_BL set BL='Payment' where DESCRIPTION='PAYMENT_ACH';
update ACTIVITY_TYPE_BL set BL='Payment' where DESCRIPTION='PAYMENT_HAMPAY';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='PAYMENT_WALLET(W2W)';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='WALLET_CASH_IN';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='WALLET_CASH_OUT';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='TOP_UP';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='INTERNET_PACKAGE';
update ACTIVITY_TYPE_BL set BL='Payment' where DESCRIPTION='PAYMENT_LINK';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='UTILITY_BILL';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='INSURANCE';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='COMMERCIAL';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='TOLL';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='TOLL_PAYOFF';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='PAYOUT_CARD';
update ACTIVITY_TYPE_BL set BL='Payment' where DESCRIPTION='REFUND_MANUAL';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='CONGESTION_PRICING';
update ACTIVITY_TYPE_BL set BL='Payment' where DESCRIPTION='REFUND_DIGIPAY';
update ACTIVITY_TYPE_BL set BL='Payment' where DESCRIPTION='REVERSE_MANUAL';
update ACTIVITY_TYPE_BL set BL='Credit' where DESCRIPTION='INSTALLMENT';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='THIRD_PARTY_TICKET';
update ACTIVITY_TYPE_BL set BL='KYC' where DESCRIPTION='CREDIT_INQUIRY';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='DONATION';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='TRAFFIC_FINE';
update ACTIVITY_TYPE_BL set BL='Payment' where DESCRIPTION='PARTNER_AGENT_PAYOUT';
update ACTIVITY_TYPE_BL set BL='Credit' where DESCRIPTION='CREDIT_PREPAYMENT';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='MARKETPLACE';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='STOCK';
update ACTIVITY_TYPE_BL set BL='Payment' where DESCRIPTION='SUBSCRIPTION';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='TAXI_PAYMENT';
update ACTIVITY_TYPE_BL set BL='App' where DESCRIPTION='VOUCHER';
update ACTIVITY_TYPE_BL set BL='Unknown' where id in (-1,4571,5492);

--daily
-- drop view vw_bourse_daily_10m
create or replace view vw_bourse_daily as
select tt.*,day_amount-pday_amount dif_amount,day_count-pday_count dif_count
from(select to_char(pdate) pdate,lpad(floor(last_time/100),2,'0')||':'||lpad(mod(last_time,100),2,'0') as last_time,at.BL,to_char(F_TYPE) f_type,at.Description type,at.p_Description ptype
          ,day_amount,LAG(day_amount) OVER (partition by f_type ORDER BY pdate) pday_amount
     ,day_count,LAG(day_count) OVER (partition by f_type ORDER BY pdate) pday_count
     from (select a.pdate,a.F_TYPE,sum(MINUTE_AMOUNT) day_amount,sum(MINUTE_COUNT) day_count,max(a.HOUR_MINUTE) last_time
           from CDC_ACTIVITIES_10MIN_AGG_OK a
           where a.HOUR_MINUTE<=to_char(sysdate,'HH24MI')
             and a.PDATE>=to_char(sysdate-1,'YYYYMMDD','nls_calendar=persian')
           group by a.pdate,a.F_TYPE)t
              left join ACTIVITY_TYPE_BL at on at.id=t.F_TYPE
    )tt where PDATE=''||to_char(sysdate,'YYYYMMDD','nls_calendar=persian')
;

select * from vw_bourse_daily;

select to_char(sysdate-1,'YYYYMMDD','nls_calendar=persian') from dual;

select trunc(sysdate-5, 'iw')+5 AS week_start_date,
       to_char(trunc(sysdate-5, 'iw')+5,'YYYYMMDDHH24MI','nls_calendar=persian'),
       to_char(sysdate,'YYYYMMDDHH24MI','nls_calendar=persian'),
       trunc(sysdate-5, 'iw')+5 + 7 - 1/86400 AS iso_week_end_date
from dual;


select
    TRUNC (sysdate, 'mm') AS month_start_date,
    to_char(sysdate, 'YYYYMM','nls_calendar=persian')||'01',
    to_char(sysdate,'DAY'),
    to_char(mongodb.JALALI_PREV_MONTH(sysdate), 'YYYYMM','nls_calendar=persian')||'01',
    to_char(sysdate,'YYYYMMDDHH24MI','nls_calendar=persian'),
    LAST_DAY (TRUNC (sysdate, 'mm')) + 1 - 1/86400 AS month_end_date
from dual;

create or replace view vw_health_weekly as
select tt.*,amount-prev_amount dif_amount,count-prev_count dif_count
from(select to_char(pdate) pdate,last_time,at.BL,to_char(F_TYPE) f_type,at.Description type,at.p_Description ptype
          ,NVL(amount,0) amount,NVL(LAG(amount) OVER (partition by f_type ORDER BY pdate),0) prev_amount
          ,NVL(count,0) count,NVL(LAG(count) OVER (partition by f_type ORDER BY pdate),0) prev_count
     from (
select to_char(trunc(sysdate-5, 'iw')+5,'YYYYMMDD','nls_calendar=persian') pdate,a.F_TYPE
    ,sum(MINUTE_AMOUNT) amount,sum(MINUTE_COUNT) count
    ,max(pdate ||' '|| lpad(floor(a.HOUR_MINUTE/100),2,'0')||':'||lpad(mod(a.HOUR_MINUTE,100),2,'0'))||'-'||to_char(sysdate,'DAY') last_time
from CDC_ACTIVITIES_10MIN_AGG_OK a
where a.pdate||lpad(a.HOUR_MINUTE,4,'0')
    between to_char(trunc(sysdate-5, 'iw')+5,'YYYYMMDDHH24MI','nls_calendar=persian')
    AND to_char(sysdate,'YYYYMMDDHH24MI','nls_calendar=persian')
GROUP BY a.F_TYPE,to_char(trunc(sysdate-5, 'iw')+5,'YYYYMMDD','nls_calendar=persian')
union all
select to_char(trunc(sysdate-5-7, 'iw')+5,'YYYYMMDD','nls_calendar=persian') pdate,a.F_TYPE
     ,sum(MINUTE_AMOUNT) amount,sum(MINUTE_COUNT) count
     ,max(pdate ||' '|| lpad(floor(a.HOUR_MINUTE/100),2,'0')||':'||lpad(mod(a.HOUR_MINUTE,100),2,'0'))||'-'||to_char(sysdate,'DAY') last_time
from CDC_ACTIVITIES_10MIN_AGG_OK a
where a.pdate||lpad(a.HOUR_MINUTE,4,'0')
          between to_char(trunc(sysdate-5-7, 'iw')+5,'YYYYMMDDHH24MI','nls_calendar=persian') AND to_char(sysdate-7,'YYYYMMDDHH24MI','nls_calendar=persian')
GROUP BY a.F_TYPE,to_char(trunc(sysdate-5-7, 'iw')+5,'YYYYMMDD','nls_calendar=persian')
)t left join ACTIVITY_TYPE_BL at on at.id=t.F_TYPE
)tt where PDATE=to_char(trunc(sysdate-5, 'iw')+5,'YYYYMMDD','nls_calendar=persian');

select * from vw_health_weekly;


create or replace view vw_health_monthly as
select tt.*,amount-prev_amount dif_amount,count-prev_count dif_count
from(select to_char(pdate) pdate,last_time,at.BL,to_char(F_TYPE) f_type,at.Description type,at.p_Description ptype
          ,NVL(amount,0) amount,NVL(LAG(amount) OVER (partition by f_type ORDER BY pdate),0) prev_amount
          ,NVL(count,0) count,NVL(LAG(count) OVER (partition by f_type ORDER BY pdate),0) prev_count
     from (
              select to_char(sysdate, 'YYYYMM','nls_calendar=persian')||'01' pdate,a.F_TYPE
                   ,sum(MINUTE_AMOUNT) amount,sum(MINUTE_COUNT) count
                   ,max(pdate ||' '|| lpad(floor(a.HOUR_MINUTE/100),2,'0')||':'||lpad(mod(a.HOUR_MINUTE,100),2,'0')) last_time
              from CDC_ACTIVITIES_10MIN_AGG_OK a
              where a.pdate||lpad(a.HOUR_MINUTE,4,'0')||'00'
                        between to_char(sysdate, 'YYYYMM','nls_calendar=persian')||'01'
                            AND to_char(sysdate,'YYYYMMDDHH24MI','nls_calendar=persian')
              GROUP BY a.F_TYPE,to_char(sysdate, 'YYYYMM','nls_calendar=persian')||'01'
              union all
              select to_char(mongodb.JALALI_PREV_MONTH(sysdate), 'YYYYMM','nls_calendar=persian')||'01' pdate,a.F_TYPE
                   ,sum(MINUTE_AMOUNT) amount,sum(MINUTE_COUNT) count
                   ,max(pdate ||' '|| lpad(floor(a.HOUR_MINUTE/100),2,'0')||':'||lpad(mod(a.HOUR_MINUTE,100),2,'0')) last_time
              from CDC_ACTIVITIES_10MIN_AGG_OK a
              where a.pdate||lpad(a.HOUR_MINUTE,4,'0')||'00'
                        between to_char(mongodb.JALALI_PREV_MONTH(sysdate), 'YYYYMM','nls_calendar=persian')||'01'
                            AND to_char(mongodb.JALALI_PREV_MONTH(sysdate),'YYYYMMDDHH24MI','nls_calendar=persian')
              GROUP BY a.F_TYPE,to_char(mongodb.JALALI_PREV_MONTH(sysdate), 'YYYYMM','nls_calendar=persian')||'01'
          )t left join ACTIVITY_TYPE_BL at on at.id=t.F_TYPE
    )tt where PDATE=to_char(sysdate, 'YYYYMM','nls_calendar=persian')||'01';

select * from vw_health_monthly;


create or replace view vw_health_daily as
select tt.*,amount-prev_amount dif_amount,count-prev_count dif_count
from(select to_char(pdate) pdate,lpad(floor(last_time/100),2,'0')||':'||lpad(mod(last_time,100),2,'0') as last_time,at.BL,to_char(F_TYPE) f_type,at.Description type,at.p_Description ptype
          ,NVL(amount,0) amount,NVL(LAG(amount) OVER (partition by f_type ORDER BY pdate),0) prev_amount
          ,NVL(count,0) count,NVL(LAG(count) OVER (partition by f_type ORDER BY pdate),0) prev_count
     from (select a.pdate,a.F_TYPE,sum(MINUTE_AMOUNT) amount,sum(MINUTE_COUNT) count,max(a.HOUR_MINUTE) last_time
           from CDC_ACTIVITIES_10MIN_AGG_OK a
           where a.HOUR_MINUTE<=to_char(sysdate,'HH24MI')
             and a.PDATE>=to_char(sysdate-1,'YYYYMMDD','nls_calendar=persian')
           group by a.pdate,a.F_TYPE)t
              left join ACTIVITY_TYPE_BL at on at.id=t.F_TYPE
    )tt where PDATE=''||to_char(sysdate,'YYYYMMDD','nls_calendar=persian')
;

select * from vw_health_daily;


select distinct a.pdate||lpad(a.HOUR_MINUTE,4,'0')
                    , to_char(trunc(sysdate-5, 'iw')+5,'YYYYMMDDHH24MI','nls_calendar=persian')
                    , to_char(sysdate,'YYYYMMDDHH24MI','nls_calendar=persian')
from CDC_ACTIVITIES_10MIN_AGG_OK a
where a.pdate||lpad(a.HOUR_MINUTE,4,'0')
          between to_char(trunc(sysdate-5, 'iw')+5,'YYYYMMDDHH24MI','nls_calendar=persian')
          AND to_char(sysdate,'YYYYMMDDHH24MI','nls_calendar=persian')
order by a.pdate||lpad(a.HOUR_MINUTE,4,'0')
;

select to_char(trunc(sysdate-5-7, 'iw')+5,'YYYYMMDD','nls_calendar=persian') pdate,a.F_TYPE
     ,sum(MINUTE_AMOUNT) amount,sum(MINUTE_COUNT) count
     ,max(pdate ||' '|| lpad(floor(a.HOUR_MINUTE/100),2,'0')||':'||lpad(mod(a.HOUR_MINUTE,100),2,'0'))||'-'||to_char(sysdate,'DAY') last_time
from CDC_ACTIVITIES_10MIN_AGG_OK a
where a.pdate||lpad(a.HOUR_MINUTE,4,'0')
          between to_char(trunc(sysdate-5-7, 'iw')+5,'YYYYMMDDHH24MI','nls_calendar=persian')
              AND to_char(sysdate-7,'YYYYMMDDHH24MI','nls_calendar=persian')
GROUP BY a.F_TYPE,to_char(trunc(sysdate-5-7, 'iw')+5,'YYYYMMDD','nls_calendar=persian')
;
select to_char(sysdate-7,'YYYYMMDDHH24MI','nls_calendar=persian') from dual;

select to_char(trunc(sysdate-5, 'iw')+5,'YYYYMMDD','nls_calendar=persian') pdate1,a.F_TYPE
    ,a.pdate,HOUR_MINUTE
     ,pdate ||' '|| lpad(floor(a.HOUR_MINUTE/100),2,'0')||':'||lpad(mod(a.HOUR_MINUTE,100),2,0) last_time
,HOUR_MINUTE,lpad(floor(a.HOUR_MINUTE/100),2,'0') h
,lpad(mod(floor(a.HOUR_MINUTE),100),2,0) m
from CDC_ACTIVITIES_10MIN_AGG_OK a
where a.pdate||lpad(a.HOUR_MINUTE,4,'0')
          between to_char(trunc(sysdate-5, 'iw')+5,'YYYYMMDDHH24MI','nls_calendar=persian')
          AND to_char(sysdate,'YYYYMMDDHH24MI','nls_calendar=persian')
-- GROUP BY a.F_TYPE,to_char(trunc(sysdate-5, 'iw')+5,'YYYYMMDD','nls_calendar=persian')
and a.F_TYPE=13 and a.PDATE='14010302'
order by a.pdate ||' '|| lpad(floor(a.HOUR_MINUTE/100),2,'0')||':'||lpad(mod(a.HOUR_MINUTE,100),2,0) desc
;




select tt.*,amount-prev_amount dif_amount,count-prev_count dif_count
from(select to_char(pdate) pdate,lpad(floor(last_time/100),2,'0')||':'||lpad(mod(last_time,100),2,'0') as last_time,at.BL,to_char(F_TYPE) f_type,at.Description type,at.p_Description ptype
          ,amount,nvl(LAG(amount) OVER (partition by f_type ORDER BY pdate),0) prev_amount
          ,count,nvl(LAG(count) OVER (partition by f_type ORDER BY pdate),0) prev_count
     from (select a.pdate,a.F_TYPE,sum(MINUTE_AMOUNT) amount,sum(MINUTE_COUNT) count,max(a.HOUR_MINUTE) last_time
           from CDC_ACTIVITIES_10MIN_AGG_OK a
           where a.HOUR_MINUTE<=to_char(sysdate,'HH24MI')
             and a.PDATE>=to_char(sysdate-1,'YYYYMMDD','nls_calendar=persian')
           group by a.pdate,a.F_TYPE)t
              left join ACTIVITY_TYPE_BL at on at.id=t.F_TYPE
    )tt where PDATE=''||to_char(sysdate,'YYYYMMDD','nls_calendar=persian')
;


