CREATE TABLESPACE TBS_FINANCE DATAFILE
    '/oracle/u01/app/oracle/oradata/dgporclw/tbs_finance00.dbf' SIZE 100M
    AUTOEXTEND ON NEXT 8192 MAXSIZE 20480M
    LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;

create user finance identified by finance default tablespace TBS_FINANCE quota unlimited on TBS_FINANCE;
grant connect,resource,create view to finance;
grant select on dim_month to finance;
grant select,insert,update on DP_AT_A_GLANCE.STG_AT_GLANCE to finance;


-- drop table FIN_MOEIN_MAPPING;
-- truncate table FIN_MOEIN_MAPPING;
create table FIN_MOEIN_MAPPING
(
    ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY primary key,
    FST varchar2(20),
    FST_01_Code varchar2(10),
    FST_01_Desc varchar2(100),
    FST_02_CODE NUMBER(10),
    FST_02_DESC varchar2(100),
    MOEIN NUMBER(10),
    FST_Product varchar2(100)
);
create index ix_MOEIN_MAPPING_MOEIN
	on FIN_MOEIN_MAPPING (MOEIN)
;
select * from FIN_MOEIN_MAPPING
where fst like '%Grand%'
;
-- delete from FIN_MOEIN_MAPPING where fst like '%Grand%';


-- drop table FIN_MOEIN_REPORT_ETL;
create table FIN_MOEIN_REPORT_ETL (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY primary key,
    ETL_DATE date default current_date,
    PYEAR INTEGER,
    PMONTH INTEGER,
    DETAIL_COUNT NUMBER(18),
    DETAIL_Debit_SUM NUMBER(18),
    DETAIL_Credit_SUM NUMBER(18),
    active NUMBER(1) default 1
);

-- drop table FIN_MOEIN_REPORT_DETAIL;
create table FIN_MOEIN_REPORT_DETAIL (
  ID NUMBER(18) GENERATED BY DEFAULT AS IDENTITY primary key,
  F_MOEIN_REPORT_ETL NUMBER(10) not null,
  GLCode       NUMBER(8),
  SLCode       NUMBER(8),
  GNumber       NUMBER(8),
  Sequence     NUMBER(8),
  DailyNumber          NUMBER(8),
  CreationDate         Date,
  LastModificationDate Date,
  VoucherItemID	    NUMBER(18),
  VoucherRef	NUMBER(18),
  BranchRef	    NUMBER(8),
  GLRef	        NUMBER(8),
  SLRef	        NUMBER(8),
  Debit	        NUMBER(18),
  Credit	    NUMBER(18),
  TargetCurrencyRef	    NUMBER(8),
  TargetCurrencyDebit	NUMBER(8),
  TargetCurrencyCredit	NUMBER(8),
  FiscalYearRef	        NUMBER(8),
  GDate	            Date,
  VoucherTypeRef	NUMBER(8),
  State	            NUMBER(8),
  LedgerRef	        NUMBER(8),
  DLLevel4	        NUMBER(18),
  DLLevel5	        NUMBER(18),
  DLLevel6	        NUMBER(18),
  DLLevel7	        NUMBER(18),
  DLLevel8	        NUMBER(18),
  DLLevel9	        NUMBER(18)
);
-- alter table FIN_MOEIN_REPORT_DETAIL add constraint fk_FIN_MOEIN_REPORT_ETL
-- foreign key (F_MOEIN_REPORT_ETL) references FIN_MOEIN_REPORT_ETL (ID);

create index IX_FIN_MOEIN_REPORT_DETAIL_ETL
    on FIN_MOEIN_REPORT_DETAIL (F_MOEIN_REPORT_ETL);

create index IX_FIN_MOEIN_REPORT_DETAIL_SLCODE
    on FIN_MOEIN_REPORT_DETAIL (SLCODE);


update (select etl.ID,etl.DETAIL_COUNT,etl.DETAIL_Credit_SUM,etl.DETAIL_Debit_SUM
            ,detail.F_MOEIN_REPORT_ETL,detail.DETAIL_COUNT2
            ,detail.DETAIL_Debit_SUM2,detail.DETAIL_Credit_SUM2
    from FIN_MOEIN_REPORT_ETL etl
    join (select F_MOEIN_REPORT_ETL,count(*) DETAIL_COUNT2
    ,sum(Debit) DETAIL_Debit_SUM2,sum(Credit) DETAIL_Credit_SUM2
    from FIN_MOEIN_REPORT_DETAIL group by F_MOEIN_REPORT_ETL) detail
    on detail.F_MOEIN_REPORT_ETL=etl.ID
    where etl.id=2)
set
    DETAIL_COUNT =DETAIL_COUNT2,
    DETAIL_Debit_SUM =DETAIL_Debit_SUM2,
    DETAIL_Credit_SUM =DETAIL_Credit_SUM2
where id=2
;

create view vw_fin_fst_balance as
select m.FST_02_CODE,m.FST_02_DESC
     ,nvl(sum(d.DEBIT),0)-nvl(sum(d.CREDIT),0) balance
    ,e.pyear,e.pmonth
from FIN_MOEIN_REPORT_DETAIL d
         full join FIN_MOEIN_MAPPING m on m.MOEIN = d.slcode
         left join FIN_MOEIN_REPORT_ETL e on e.ID=d.F_MOEIN_REPORT_ETL
where e.active=1
group by m.FST_02_CODE,m.FST_02_DESC,e.pyear,e.pmonth
;

select * from finance.vw_fin_fst_balance
pivot (sum(balance) for pmonth in (1 فروردین,2 اردیبهشت,3 خرداد,4 تیر,5 مرداد,6 شهریور,7 مهر,8 آبان,9 آذر,10 دی,11 بهمن,12 اسفند))
order by FST_02_CODE
;
-- CP_MONGODB
;
select TO_CHAR(TO_DATE(7, 'MM','nls_calendar=persian'), 'MONTH','nls_calendar=persian') from dual;
;
with fst_balance as
( select to_char(FST_02_CODE) FST_02_CODE, FST_02_DESC,to_char(pyear) pyear,to_char(pmonth) pmonth,balance
from finance.vw_fin_fst_balance
    order by pmonth)
select * from fst_balance
pivot (sum(balance) for pmonth in (1 فروردین,2 اردیبهشت,3 خرداد,4 تیر,5 مرداد,6 شهریور,7 مهر,8 آبان,9 آذر,10 دی,11 بهمن,12 اسفند))
order by FST_02_CODE
;


select to_char(FST_02_CODE) FST_02_CODE, FST_02_DESC,to_char(pyear) pyear,to_char(pmonth) pmonth,balance
     ,lpad(pmonth,2,'0')||'-'|| case pmonth when 1 then 'فروردین'when 2 then 'اردیبهشت' when 3 then 'خرداد'
        when 4 then 'تیر' when 5 then 'مرداد'when 6 then 'شهریور'
        when 7 then 'مهر' when 8 then 'آبان'when 9 then 'آذر'
        when 10 then 'دی' when 11 then 'بهمن'when 12 then 'اسفند'
        else '(نامشخص)' end pmonthname
from finance.vw_fin_fst_balance
order by lpad(FST_02_CODE,4,0),pmonth
;



-- drop table fin_statement_mapping;
create table fin_statement_mapping (
    ID NUMBER(18) GENERATED BY DEFAULT AS IDENTITY primary key,
    statement varchar2(100) not null,
    category varchar2(100) not null,
    subcategory varchar2(100) ,
    subcategory2 varchar2(100) ,
    product varchar2(100) not null,
    fst_02_code NUMBER(8),
    excel_formula varchar2(1000)
);
-- alter table fin_statement_mapping add (subcategory2 varchar2(100))
-- alter table fin_statement_mapping rename column glcode to fst_02_code;
truncate table fin_statement_mapping;

insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','1-Revenue','a)SuperApp','Bill',0101);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','1-Revenue','a)SuperApp','Top-Up',0102);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','1-Revenue','a)SuperApp','InternetPackage',0103);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','1-Revenue','a)SuperApp','Shaparak',0104);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','1-Revenue','b)CreditManagement','Consumer Credit',0105);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','1-Revenue','b)CreditManagement','BNPL',0111);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','1-Revenue','c)Payment','IPG',0106);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','1-Revenue','c)Payment','Refund',0107);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','1-Revenue','c)Payment','Wallet',0108);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','1-Revenue',null,'CreditScoring',0109);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','1-Revenue',null,'KYC',0112);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','1-Revenue','d)InsureTech','InsureTech',0110);

insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','2-Cost of Revenue','a)SuperApp','Bill',0201);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','2-Cost of Revenue','a)SuperApp','Top-Up',0202);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','2-Cost of Revenue','a)SuperApp','InternetPackage',0203);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','2-Cost of Revenue','b)CreditManagement','Consumer Credit',0204);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','2-Cost of Revenue','b)CreditManagement','BNPL',0211);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','2-Cost of Revenue','c)Payment','IPG',0205);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','2-Cost of Revenue','c)Payment','Refund',0206);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','2-Cost of Revenue','c)Payment','Wallet',0207);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','2-Cost of Revenue',null,'CreditScoring',0208);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','2-Cost of Revenue',null,'KYC',0212);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','2-Cost of Revenue',null,'Wealth',0213);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','2-Cost of Revenue',null,'InsureTech',0210);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','2-Cost of Revenue',null,'HR: Transfered From SG&A',0209);

insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','3-Operation Expenses',null,'SMS',0300);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','3-Operation Expenses',null,'HR: OPS',0301);

insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','4-Marketing Expenses',null,'Marketing',0400);

insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Salary and Related',0500);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Staff Other Expenses',0501);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Rent and Related',0502);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Foods and Related',0503);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Consultancy',0504);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Tangible Assets Maintenance',0505);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Intangible Assets Maintenance',0506);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Internet',0507);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Depreciation',0508);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Amortization',0509);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Guard',0510);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Audit',0511);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Stationary and Supply',0512);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Other Expenses',0599);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Transfered to Cost of Revenue',0513);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Transfered to Product Under Development',0514);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Transferred to D&A',0515);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Transferred to salary',0516);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','5-Selling, General and Administrative Expenses',null,'Transferred to Other',0517);

insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','6-Other Operational Revenue and (Expenses)',null,'Other Operational Revenue',0698);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','6-Other Operational Revenue and (Expenses)',null,'Other Operational Expenses',0699);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','6-Other Operational Revenue and (Expenses)',null,'Transfered to Product Under Development',0600);

insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','7-Non-Operational Revenue and (Expenses)',null,'Bad Debt',0700);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','7-Non-Operational Revenue and (Expenses)',null,'Bank Interest',0701);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','7-Non-Operational Revenue and (Expenses)',null,'Bank Fee',0702);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','7-Non-Operational Revenue and (Expenses)',null,'Tax',0703);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('A)Statement of Profit or Loss','7-Non-Operational Revenue and (Expenses)',null,'Transfered to Product Under Development',0704);

insert into fin_statement_mapping (statement,category,subcategory,subcategory2,product,fst_02_code) values ('B)Statement of Financial Position','1-Non-Current Assets','a)Tangible Assets - Net','Tangible Assets','Properties and Equipment',0800);
insert into fin_statement_mapping (statement,category,subcategory,subcategory2,product,fst_02_code) values ('B)Statement of Financial Position','1-Non-Current Assets','a)Tangible Assets - Net','Tangible Assets','Computers, Data Centers and Accessories',0801);
insert into fin_statement_mapping (statement,category,subcategory,subcategory2,product,fst_02_code) values ('B)Statement of Financial Position','1-Non-Current Assets','a)Tangible Assets - Net','Tangible Assets','Refurbishment in Rental Unit',0802);
insert into fin_statement_mapping (statement,category,subcategory,subcategory2,product,fst_02_code) values ('B)Statement of Financial Position','1-Non-Current Assets','a)Tangible Assets - Net','Accumulated Depreciation','Properties and Equipment',0803);
insert into fin_statement_mapping (statement,category,subcategory,subcategory2,product,fst_02_code) values ('B)Statement of Financial Position','1-Non-Current Assets','a)Tangible Assets - Net','Accumulated Depreciation','Computers, Data Centers and Accessories',0804);
insert into fin_statement_mapping (statement,category,subcategory,subcategory2,product,fst_02_code) values ('B)Statement of Financial Position','1-Non-Current Assets','a)Tangible Assets - Net','Accumulated Depreciation','Refurbishment in Rental Unit',0805);

insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','1-Non-Current Assets','b)Intangible Assets - Net','Intangible Assets',0806);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','1-Non-Current Assets','b)Intangible Assets - Net','Accumulated Amortization',0807);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','1-Non-Current Assets',null,'Products Under Development',0808);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','1-Non-Current Assets',null,'Products Under Development: Transfered From P&L',0810);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','1-Non-Current Assets',null,'Prepayment',0809);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','1-Non-Current Assets',null,'Other Assets',0899);

insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','2-Current Assets',null,'VAT Receivable',0904);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','2-Current Assets',null,'Prepayment',0900);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','2-Current Assets',null,'Non-Trade Receivable',0901);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','2-Current Assets',null,'Trade Receivable',0902);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','2-Current Assets',null,'Trade Receivable-Refund',0905);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','2-Current Assets',null,'Cash and Banks',0903);

insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','3-Equity',null,'Shared Capital',1000);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','3-Equity',null,'Quasi Amount',1001);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','3-Equity',null,'Accumulated Profit/(Loss)',1002);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','3-Equity',null,'Prior Period Adjustment',1003);

insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','4-Non-Current Liabilities',null,'Staff Termination Benefit',1100);

insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','5-Current Liabilities',null,'Provision',1200);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','5-Current Liabilities',null,'VAT Payable',1201);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','5-Current Liabilities',null,'Advances Received',1202);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','5-Current Liabilities',null,'Non-Trade Payable',1203);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','5-Current Liabilities',null,'Trade Payable',1204);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','5-Current Liabilities',null,'Trade Payable-Refund',1206);
insert into fin_statement_mapping (statement,category,subcategory,product,fst_02_code) values ('B)Statement of Financial Position','5-Current Liabilities',null,'Credit Line Financing',1205);

-------------------  FST  -----------------------
create table FIN_FST as select distinct fst,FST_01_Code,fst_01_desc,FST_02_Code,fst_02_desc,FST_Product from FIN_MOEIN_MAPPING;
alter table FIN_FST add constraint pk_FIN_FST primary key (FST_02_Code);
create table FIN_FST_MOEIN as select distinct FST_02_Code,MOEIN,0 as DLLevel5 from FIN_MOEIN_MAPPING;
alter table FIN_FST_MOEIN add constraint pk_FIN_FST_MOEIN primary key (FST_02_Code,moein,DLLevel5);


/*
create or replace view vw_fin_actual_deck_slcode as
select pyear,pmonth,d.slcode,d.fst_02_code
    ,s.statement,s.category,s.subcategory,s.subcategory2,s.product
    ,sum(balance) balance from
(select case when d.SLCode=411303 and d.DLLevel5=998001 then 104
            when d.SLCode=511114 and d.DLLevel5=999006 then 301
            else m.FST_02_CODE end FST_02_CODE
      ,d.SLCode
     ,nvl(d.DEBIT,0)-nvl(d.CREDIT,0) balance
     ,e.pyear,e.pmonth
from FIN_MOEIN_REPORT_DETAIL d
left join FIN_MOEIN_REPORT_ETL e on e.ID=d.F_MOEIN_REPORT_ETL
left join FIN_MOEIN_MAPPING m on m.MOEIN = d.slcode
where e.active=1
) d
left join FIN_STATEMENT_MAPPING s on s.fst_02_code=d.FST_02_CODE
group by pyear,pmonth,statement,category,subcategory,subcategory2,d.slcode,d.fst_02_code,s.product
;
*/

create or replace view VW_FIN_ACTUAL_DECK_SLCODE as
select pyear,pmonth,d.slcode,d.fst_02_code
     ,s.statement,s.category,s.CATEGORY_CODE,s.subcategory,s.subcategory2,s.product
     ,sum(balance) balance from
    (select m.FST_02_CODE
          ,d.SLCode
          ,nvl(d.DEBIT,0)-nvl(d.CREDIT,0) balance
          ,e.pyear,e.pmonth
     from FIN_MOEIN_REPORT_DETAIL d
              left join FIN_MOEIN_REPORT_ETL e on e.ID=d.F_MOEIN_REPORT_ETL
              left join FIN_FST_MOEIN m on m.MOEIN = d.slcode
     where e.active=1 and (m.DLLEVEL5=0 or m.DLLEVEL5 is null)
    ) d
        left join FIN_STATEMENT_MAPPING s on s.fst_02_code=d.FST_02_CODE
group by pyear,pmonth,statement,category,CATEGORY_CODE,subcategory,subcategory2,d.slcode,d.fst_02_code,s.product
;


-- drop view vw_fin_statement_int_tax_dep_amor;
create or replace view vw_fin_statement_int_tax_dep_amor as
with q_yearmonth as (select distinct pyear,pmonth from fin_moein_report_etl where active=1)
   ,q_balance as (select nvl(sum(d.balance),0) balance, FST_02_CODE, pyear, pmonth
                  from vw_fin_actual_deck_slcode d
                  group by FST_02_CODE, pyear, pmonth)
select * from
(select 'A)Statement of Profit or Loss' statement,'8-Interest + Tax + Depreciation + Amortization' category,null subcategory,null subcategory2 from dual) s
,(select 'Interest (Credit Facilities Expenses)' product,null FST_02_CODE,pyear,pmonth
     ,0 balance from q_yearmonth union all
select 'Tax' product,null FST_02_CODE,pyear,pmonth pmonth
     ,(select -balance from q_balance b where b.fst_02_code=703 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ) balance
    from q_yearmonth ym union all
select 'Depreciation' product,null FST_02_CODE,pyear,pmonth
     ,(select balance from q_balance b where b.fst_02_code=508 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ) balance
    from q_yearmonth ym union all
select 'Amortization' product,null FST_02_CODE,pyear,pmonth
     ,(select balance from q_balance b where b.fst_02_code=509 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ) balance
    from q_yearmonth ym union all
select 'Transferred to D&A' product,null FST_02_CODE,pyear,pmonth
     ,(select balance from q_balance b where b.fst_02_code=515 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ) balance
    from q_yearmonth ym
)
;

select * from vw_fin_statement_int_tax_dep_amor;

-- drop view vw_fin_statement_specials

create or replace view VW_FIN_STATEMENT_SPECIALS as
with q_yearmonth as (select distinct pyear,pmonth from fin_moein_report_etl where active=1)
   ,q_fst_balance as (select nvl(sum(d.balance), 0) balance, FST_02_CODE, pyear, pmonth
                      from vw_fin_actual_deck_slcode d group by FST_02_CODE, pyear, pmonth)
   ,q_cat_balance as (select sum(balance) balance,category_code,category,pyear,pmonth from vw_fin_actual_deck_slcode group by category_code,category,pyear,pmonth)
   ,q_pc1 as (select 'PC1' category_code, '01' FST_02_CODE,'PC1' product,pyear,pmonth
                   ,-nvl((select balance from q_cat_balance b where b.category_code=1 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0)
        -nvl((select balance from q_cat_balance b where b.category_code=2 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
              from q_yearmonth ym group by pyear,pmonth)
   ,q_pc2 as (select 'PC2' category_code, '02' FST_02_CODE,'PC2' product,pyear,pmonth
                   ,nvl((select balance from q_pc1 b where b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0)
        -nvl((select balance from q_cat_balance b where b.category_code=3 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
              from q_yearmonth ym group by pyear,pmonth)
   ,q_pc3 as (select 'PC3' category_code, '03' FST_02_CODE,'PC3' product,pyear,pmonth
                   ,nvl((select balance from q_pc2 b where b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0)
        -nvl((select balance from q_cat_balance b where b.category_code=4 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
              from q_yearmonth ym group by pyear,pmonth)
   ,q_opl as (select 'OP/L' category_code, '04' FST_02_CODE,'Operational Profit or (Loss)' product,pyear,pmonth
                   ,nvl((select balance from q_pc3 b where b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0)
        -nvl((select balance from q_cat_balance b where b.category_code=5 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0)
        -nvl((select balance from q_cat_balance b where b.category_code=6 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
              from q_yearmonth ym group by pyear,pmonth)
   ,q_npl as (select 'NP/L' category_code, '05' FST_02_CODE,'Net Profit or (Loss)' product,pyear,pmonth
                   ,nvl((select balance from q_opl b where b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0)
        -nvl((select balance from q_cat_balance b where b.category_code=7 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
              from q_yearmonth ym group by pyear,pmonth)
   ,q_ebitda as (select 'EBITDA' category_code, '06' FST_02_CODE,'EBITDA' product,pyear,pmonth
                      ,nvl((select balance from q_npl b where b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0)
        +nvl((select sum(balance) balance from vw_fin_statement_int_tax_dep_amor b where b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
                 from q_yearmonth ym group by pyear,pmonth)
/*
   ,q_assets as (select 'PC1' category_code, '07' FST_02_CODE,'Total Assets' product,pyear,pmonth
                      ,nvl((select balance from q_cat_balance b where b.category_code=1 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0)
        +nvl((select balance from q_cat_balance b where b.category_code=2 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
                 from q_yearmonth ym group by pyear,pmonth)
   ,q_liabilities as (select '08' FST_02_CODE,'Total Liabilities' product,pyear,pmonth
                           ,nvl((select balance from q_cat_balance b where b.category_code=4 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0)
        +nvl((select balance from q_cat_balance b where b.category_code=5 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
                      from q_yearmonth ym group by pyear,pmonth)
   ,q_equity_liabilities as (select '09' FST_02_CODE,'Total Equity +  Liabilities' product,pyear,pmonth
                                  ,nvl((select balance from q_liabilities b where b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0)
                                       +nvl((select balance from q_cat_balance b where b.category_code=3 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0)
        -nvl((select balance from q_npl b where b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0)balance
                             from q_yearmonth ym group by pyear,pmonth)
   ,q_refund as (select '10' FST_02_CODE,'Refund Working Capital' product,pyear,pmonth
                      ,nvl((select sum(balance) from q_fst_balance b where b.fst_02_code=905 and b.pyear=ym.pyear and b.pmonth=ym.pmonth ),0)
        +nvl((select sum(balance) from q_fst_balance b where b.fst_02_code=1206 and b.pyear=ym.pyear and b.pmonth=ym.pmonth ),0) balance
                 from q_yearmonth ym group by pyear,pmonth)
*/
select "STATEMENT",category,category_code,"SUBCATEGORY","SUBCATEGORY2","FST_02_CODE","PRODUCT","PYEAR","PMONTH","BALANCE" from
    (select 'C)Statement of Specials' statement,null category,null subcategory,null subcategory2 from dual) s
 ,(select * from q_pc1 union all
   select * from q_pc2 union all
   select * from q_pc3 union all
   select * from q_opl union all
   select * from q_npl union all
   select * from q_ebitda /*union all
   select * from q_assets union all
   select * from q_liabilities union all
   select * from q_equity_liabilities union all
   select * from q_refund*/
    )

;

select * from vw_fin_statement_specials;


create or replace view vw_fin_statement_of_cash_flow as
with q_yearmonth as (select distinct pyear,pmonth from fin_moein_report_etl where active=1)
,q_fst_balance as (select nvl(sum(d.balance), 0) balance, FST_02_CODE, pyear, pmonth
                    from vw_fin_actual_deck_slcode d group by FST_02_CODE, pyear, pmonth)
,q_cashflow_no_refund as
    (select '2-Operating Cash Flow (Refund Excluded)' category,'EBITDA' product,null subcategory,pyear,pmonth
         ,nvl((select balance from q_fst_balance b where b.fst_02_code=1003 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0)
    +nvl((select balance from vw_fin_statement_specials b where b.product='EBITDA' and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
    from q_yearmonth ym union all
    select '2-Operating Cash Flow (Refund Excluded)' category,'Tax' product,null subcategory,pyear,pmonth
         ,nvl((select balance from q_fst_balance b where b.fst_02_code=703 and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
    from q_yearmonth ym union all
    select '2-Operating Cash Flow (Refund Excluded)' category,'Current Assets (Refund Excluded)' product,'Changes in Working Capital' subcategory,pyear,pmonth
         ,-nvl((select sum(balance) from q_fst_balance b where b.fst_02_code in (900,901,902,904) and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
    from q_yearmonth ym union all
    select '2-Operating Cash Flow (Refund Excluded)' category,'Current Liabilities (Refund Excluded)' product,'Changes in Working Capital' subcategory,pyear,pmonth
         ,-nvl((select sum(balance) from q_fst_balance b where b.fst_02_code in (1100,1200,1201,1202,1203,1204,1205) and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
    from q_yearmonth ym union all
    select '2-Operating Cash Flow (Refund Excluded)' category,'Others (Refund Excluded)' product,'Changes in Working Capital' subcategory,pyear,pmonth
         ,-nvl((select sum(balance) from q_fst_balance b where b.fst_02_code in (508,515,800,801,802,803,804,805,809,899) and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
    from q_yearmonth ym)
,q_cash_flow_with_refund as
    (select '1-Operating Cash Flow (Refund Included)' category,'Operating Cash Flow (Refund Excluded)' product,null subcategory,pyear,pmonth
              ,nvl((select sum(balance) from q_cashflow_no_refund b where b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
         from q_yearmonth ym union all
     select '1-Operating Cash Flow (Refund Included)' category,'Current Assets (Refund)' product,null subcategory,pyear,pmonth
              ,-nvl((select sum(balance) from q_fst_balance b where b.fst_02_code in (905) and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
         from q_yearmonth ym union all
     select '1-Operating Cash Flow (Refund Included)' category,'Current Liabilities (Refund)' product,null subcategory,pyear,pmonth
              ,-nvl((select sum(balance) from q_fst_balance b where b.fst_02_code in (1206) and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
         from q_yearmonth ym )
,q_cash_flow_invest as
    (select '3-Investing Cash Flow' category,'Tangible Asset Purchase / (Sale)' product,null subcategory,pyear,pmonth
          ,-nvl((select sum(balance) from q_fst_balance b where b.fst_02_code in (0800,0801,0802,0803,0804,0805,0809,0899,508,515) and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
     from q_yearmonth ym union all
     select '3-Investing Cash Flow' category,'Intangible Asset Purchase / (Sale)' product,null subcategory,pyear,pmonth
          ,-nvl((select sum(balance) from q_fst_balance b where b.fst_02_code in (0806,0807,0808,0810,509) and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
     from q_yearmonth ym)
,q_cash_flow_finance as
    (select '4-Financing Cash Flow' category,'Shared Capital' product,null subcategory,pyear,pmonth
          ,nvl((select sum(balance) from q_fst_balance b where b.fst_02_code in (1000) and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
     from q_yearmonth ym union all
     select '4-Financing Cash Flow' category,'Injected Fund Thorough Investors' product,null subcategory,pyear,pmonth
          ,nvl((select sum(balance) from q_fst_balance b where b.fst_02_code in (1001) and b.PYEAR=ym.PYEAR and b.PMONTH=ym.PMONTH ),0) balance
     from q_yearmonth ym)
,q_cash_flow_begin as (
    select '5-Cash at the Beginning of Period' category,'Cash at the Beginning' product,null subcategory,pyear,pmonth
     ,nvl((select sum(balance) from q_cash_flow_with_refund b where b.PYEAR*100+b.PMONTH < ym.PYEAR*100+ym.PMONTH ),0)
     +nvl((select sum(balance) from q_cash_flow_invest b where b.PYEAR*100+b.PMONTH < ym.PYEAR*100+ym.PMONTH ),0)
     +nvl((select sum(balance) from q_cash_flow_finance b where b.PYEAR*100+b.PMONTH < ym.PYEAR*100+ym.PMONTH ),0) balance
    from q_yearmonth ym)
,q_cash_flow_end as (
    select '6-Cash at the End of Period' category, 'Cash at the End' product,null subcategory,pyear,pmonth
     ,nvl((select sum(balance) from q_cash_flow_with_refund b where b.PYEAR*100+b.PMONTH <= ym.PYEAR*100+ym.PMONTH ),0)
     +nvl((select sum(balance) from q_cash_flow_invest b where b.PYEAR*100+b.PMONTH <= ym.PYEAR*100+ym.PMONTH ),0)
     +nvl((select sum(balance) from q_cash_flow_finance b where b.PYEAR*100+b.PMONTH <= ym.PYEAR*100+ym.PMONTH ),0) balance
    from q_yearmonth ym)

select * from(select 'D)Statement of Cash Flow' statement,null subcategory2,null FST_02_CODE from dual) s
,(
    select * from q_cash_flow_with_refund union all
    select * from q_cashflow_no_refund union all
    select * from q_cash_flow_invest union all
    select * from q_cash_flow_finance union all
    select * from q_cash_flow_begin union all
    select * from q_cash_flow_end
)
;
--

create or replace view vw_fin_actual_deck as
create view VW_FIN_ACTUAL_DECK as
select FST_02_CODE,STATEMENT,CATEGORY,SUBCATEGORY,SUBCATEGORY2,PRODUCT,sum(BALANCE) balance, pyear, pmonth,category_code from vw_fin_actual_deck_slcode
group by FST_02_CODE,STATEMENT,CATEGORY,SUBCATEGORY,SUBCATEGORY2,PRODUCT, pyear, pmonth,category_code
/*union all
select FST_02_CODE,STATEMENT,CATEGORY,SUBCATEGORY,SUBCATEGORY2,PRODUCT,BALANCE,PYEAR,PMONTH,category_code from vw_fin_statement_int_tax_dep_amor
  */
union all
select to_number(FST_02_CODE),STATEMENT,CATEGORY,SUBCATEGORY,SUBCATEGORY2,PRODUCT,BALANCE,PYEAR,PMONTH,category_code from vw_fin_statement_specials
union all
select FST_02_CODE,STATEMENT,CATEGORY,SUBCATEGORY,SUBCATEGORY2,PRODUCT,BALANCE,PYEAR,PMONTH,category_code from vw_fin_statement_of_cash_flow
;

select * from vw_fin_actual_deck;

-- obi direct query for actual_deck
        select nvl(d.statement,'«نامشخص»') as statement,d.category,d.subcategory,d.subcategory2,lpad(FST_02_CODE,4,' ')||'-'||nvl(d.product,'«نامشخص»') as product
     ,lpad(FST_02_CODE,4,' ') FST_02_CODE,to_char(pyear) pyear,to_char(pmonth) pmonth,balance
     ,lpad(pmonth,2,'0')||'-'|| case pmonth when 1 then 'فروردین'when 2 then 'اردیبهشت' when 3 then 'خرداد'
                                            when 4 then 'تیر' when 5 then 'مرداد'when 6 then 'شهریور'
                                            when 7 then 'مهر' when 8 then 'آبان'when 9 then 'آذر'
                                            when 10 then 'دی' when 11 then 'بهمن'when 12 then 'اسفند'
                                            else '«نامشخص»' end pmonthname
from finance.vw_fin_actual_deck d
order by lpad(FST_02_CODE,4,' ')||'-'||nvl(d.product,'«نامشخص»')
;




create or replace view vw_fin_at_glance_bak as
select 'Revenue' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,9 as KPI, 'Rahkaran' as KPI_DETAILS
     ,sum(BALANCE) MEASURE
from FINANCE.VW_FIN_ACTUAL_DECK d
left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where CATEGORY='1-Revenue'
group by m.LAST_DAY_OF_MONTH
union all
select 'Profit Contribution 1' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,10 as KPI, 'Rahkaran' as KPI_DETAILS
     ,sum(BALANCE) MEASURE
from FINANCE.VW_FIN_ACTUAL_DECK d
         left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where PRODUCT='PC1'
group by m.LAST_DAY_OF_MONTH
union all
select 'Profit Contribution 2' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,19 as KPI, 'Rahkaran' as KPI_DETAILS
     ,sum(BALANCE) MEASURE
from FINANCE.VW_FIN_ACTUAL_DECK d
         left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where PRODUCT='PC2'
group by m.LAST_DAY_OF_MONTH
union all
select 'Profit Contribution 3' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,20 as KPI, 'Rahkaran' as KPI_DETAILS
     ,sum(BALANCE) MEASURE
from FINANCE.VW_FIN_ACTUAL_DECK d
         left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where PRODUCT='PC3'
group by m.LAST_DAY_OF_MONTH
union all
select 'EBITDA' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,11 as KPI, 'Rahkaran' as KPI_DETAILS
     ,sum(BALANCE) MEASURE
from FINANCE.VW_FIN_ACTUAL_DECK d
         left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where PRODUCT='EBITDA'
group by m.LAST_DAY_OF_MONTH
union all
select 'Operating Cash Flow' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,12 as KPI, 'Rahkaran' as KPI_DETAILS
     ,sum(BALANCE) MEASURE
from FINANCE.VW_FIN_ACTUAL_DECK d
         left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where category='1-Operating Cash Flow (Refund Included)'
group by m.LAST_DAY_OF_MONTH
union all
select 'PBT' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,17 as KPI, 'Rahkaran' as KPI_DETAILS
     ,sum(BALANCE) MEASURE
from FINANCE.VW_FIN_ACTUAL_DECK d
         left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where PRODUCT='Net Profit or (Loss)'
group by m.LAST_DAY_OF_MONTH

;

-- create index ix_vw_fin_at_glance on vw_fin_at_glance(kpi,PDATE);
-- delete from DP_AT_A_GLANCE.STG_AT_GLANCE where kpi in (9,10,11,12,17);

select GDATE,PDATE,KPI,KPI_DETAILS,MEASURE
from FINANCE.vw_fin_at_glance d
where d.PDATE=14010231 and d.kpi=11

-- update dp_at_a_glance.ft_at_glance s
-- set s.yoy_measure = (select ss.measure from dp_at_a_glance.ft_at_glance ss where ss.kpi = s.kpi and s.yoy_date = ss.pdate)
-- where s.pdate >=13970101 ;
--
-- update dp_at_a_glance.ft_at_glance s
-- set s.mom_measure = (select ss.measure from dp_at_a_glance.ft_at_glance ss where ss.kpi = s.kpi and s.mom_date = ss.pdate)
-- where s.pdate >= 13970101;

-- create table FIN_MOEIN_MAPPING_010322_bak as
--     select * from FIN_MOEIN_MAPPING;
-- select count(*) from FIN_MOEIN_MAPPING_010322_bak;

-- create table fin_fst_moein_history as
-- select sysdate as modified_date,fm.* from FIN_FST_MOEIN fm
-- where 1=0
-- ;

-- insert into fin_fst_moein_history
-- select to_date('14010206','yyyymmdd','nls_calendar=persian') as modified_date
-- ,fm.fst_02_code,fm.moein,0 as dllevel5 from FIN_MOEIN_MAPPING_010322_bak fm
;

-- insert into fin_fst_moein_history
-- select sysdate as modified_date,fm.fst_02_code,fm.moein,fm.dllevel5 from FIN_FST_MOEIN fm
-- ;

select to_char(balance,'999,999,999,999') balance,d.* from vw_fin_actual_deck d
where pyear=1401 and pmonth=2
;
-- select * from FIN_FST_MOEIN fm
-- left join FIN_FST FF on fm.FST_02_Code = FF.FST_02_CODE
-- where fm.FST_02_Code=500
-- ;

-- select pyear,pmonth,* from vw_fin_statement_of_cash_flow c
select pyear,pmonth,sum(balance) b from vw_fin_statement_of_cash_flow c
where 1=1
-- and c.pyear=1401 and c.pmonth=2
and c.category='1-Operating Cash Flow (Refund Included)'
group by pyear,pmonth
order by pyear,pmonth
;
select pyear,pmonth,sum(balance) b from vw_fin_statement_of_cash_flow c
where 1=1
-- and c.pyear=1401 and c.pmonth=2
and c.category='1-Operating Cash Flow (Refund Included)'
group by pyear,pmonth
order by pyear,pmonth
;

select distinct slcode from FIN_MOEIN_REPORT_DETAIL d
left join FIN_MOEIN_REPORT_ETL e on e.ID=d.F_MOEIN_REPORT_ETL
where e.active=1
;

select * from fin_statement_mapping;

select * from FIN_FST_MOEIN;


create table FST_BUDGET_SCENARIO
(
    ID NUMBER(10) primary key,
    NAME VARCHAR2(100) not null,
    DESCRIPTION VARCHAR2(1000)
);
create unique index UK_FST_BUDGET_SCENARIO on FST_BUDGET_SCENARIO(NAME);
insert into FST_BUDGET_SCENARIO values (1,'Budget',null);
insert into FST_BUDGET_SCENARIO values (2,'Optimistically',null);
insert into FST_BUDGET_SCENARIO values (3,'Realistic',null);
insert into FST_BUDGET_SCENARIO values (4,'Pessimistic',null);

create table FST_BUDGET_CATEGORY
(
    ID NUMBER(10) primary key,
    NAME VARCHAR2(100) not null,
    DESCRIPTION VARCHAR2(1000)
);
create unique index UK_FST_BUDGET_CATEGORY on FST_BUDGET_CATEGORY(NAME);
insert into FST_BUDGET_CATEGORY values (1,'Financial','source-data:google-sheets/FP&A_DATA/Financial Statement , link: https://docs.google.com/spreadsheets/d/1BwD2OvPzWPk4fsJeJdNhKvyDysicKmDKo4nSR8yE1-8/edit#gid=2085615360');
insert into FST_BUDGET_CATEGORY values (2,'Assumption','source-data:google-sheets/FP&A_DATA/Assumption_KPIs , link: https://docs.google.com/spreadsheets/d/1BwD2OvPzWPk4fsJeJdNhKvyDysicKmDKo4nSR8yE1-8/edit#gid=1645291741');

create table FST_BUDGET_TYPE
(
    ID NUMBER(10) primary key,
    NAME VARCHAR2(100) not null,
    IS_CALC_BY_PREV_Q NUMBER(1) default 0
);
create unique index uk_FST_BUDGET_TYPE on FST_BUDGET_TYPE(NAME);
insert into FST_BUDGET_TYPE values (1,'12+0',0);
insert into FST_BUDGET_TYPE values (2,'3+9',1);
insert into FST_BUDGET_TYPE values (3,'6+6',1);
insert into FST_BUDGET_TYPE values (4,'9+3',1);

create table FST_BUDGET
(
    ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY primary key,
    PYEAR NUMBER(4) not null,
    PMONTH NUMBER(2) not null,
    F_FST_BUDGET_SCENARIO NUMBER(10) default 1 not null ,
    F_FST_BUDGET_CATEGORY NUMBER(10) not null,
    F_FST_BUDGET_TYPE NUMBER(10) not null,
    KPI_KEY VARCHAR2(20) not null,
    VALUE NUMBER(18) not null,
    create_date date default sysdate,
    last_modified_date date
);
create unique index UK_FST_BUDGET
    on FST_BUDGET (PYEAR,PMONTH,F_FST_BUDGET_SCENARIO,F_FST_BUDGET_CATEGORY,F_FST_BUDGET_TYPE,KPI_KEY)
;

create table FST_BUDGET_HISTORY as
select sysdate as modified_date,fb.* from FST_BUDGET fb
where 1=0
;

-- مراحل قبل از درج اطلاعات بودجه
-- :F_FST_BUDGET_SCENARIO=1
-- 1
insert into FST_BUDGET_HISTORY
select sysdate as modified_date
,fb.ID,fb.PYEAR ,fb.PMONTH,fb.F_FST_BUDGET_SCENARIO,fb.F_FST_BUDGET_CATEGORY,fb.F_FST_BUDGET_TYPE,fb.KPI_KEY,fb.VALUE,fb.create_date,fb.last_modified_date
from FST_BUDGET fb
where PYEAR=:PYEAR
  and F_FST_BUDGET_SCENARIO=:F_FST_BUDGET_SCENARIO
  and F_FST_BUDGET_CATEGORY=:F_FST_BUDGET_CATEGORY
;
-- 2
delete from FST_BUDGET
where PYEAR=:PYEAR
  and F_FST_BUDGET_SCENARIO=:F_FST_BUDGET_SCENARIO
  and F_FST_BUDGET_CATEGORY=:F_FST_BUDGET_CATEGORY
;
-- 3
insert into FST_BUDGET (PYEAR,PMONTH,F_FST_BUDGET_SCENARIO,F_FST_BUDGET_CATEGORY,F_FST_BUDGET_TYPE,KPI_KEY,VALUE)
values (:PYEAR,:PMONTH,:F_FST_BUDGET_SCENARIO,:F_FST_BUDGET_CATEGORY,:F_FST_BUDGET_TYPE,:KPI_KEY,:VALUE)
;


select GDATE,PDATE,KPI,KPI_DETAILS,MEASURE
from FINANCE.vw_fin_at_glance d
-- where not exists(select * from DP_AT_A_GLANCE.STG_AT_GLANCE sg where sg.kpi=d.kpi and sg.PDATE=d.pdate)
where kpi=9 --and PDATE=14010131


select 'Revenue' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,9 as KPI, 'Rahkaran' as KPI_DETAILS
     ,sum(BALANCE) MEASURE
from FINANCE.VW_FIN_ACTUAL_DECK d
         left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where CATEGORY_CODE =1
group by m.LAST_DAY_OF_MONTH
;
select *
from FINANCE.VW_FIN_ACTUAL_DECK d
where category like '%Revenue%'
;
select * from finance.FIN_STATEMENT_MAPPING
-- where CATEGORY like '%Revenue%'
where CATEGORY_CODE =1
;


select * from VW_FIN_FST_STATMENT
where FST_01_DESC='PC1' and pyear=1401 and pmonth=1
;

select * from VW_FIN_FST_STATMENT
where pyear=1401 and pmonth=1
;



select 'Revenue' kpi_name,to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
 ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
 ,9 as KPI, 'Rahkaran' as KPI_DETAILS
 ,BALANCE MEASURE
from VW_FIN_FST_STATMENT s
left join mongodb.dim_month m on m.p_yearmonth=(s.PYEAR*100+s.pmonth)
where FST_01_CODE='1'
  and pyear=1401 and pmonth=1
;
select * from mongodb.dim_month;
;

create or replace view vw_fin_at_glance as
select 'Revenue' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,9 as KPI, 'Rahkaran' as KPI_DETAILS
     ,BALANCE MEASURE
from VW_FIN_FST_STATMENT d
         left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where FST_01_CODE='1'
union all
select 'Profit Contribution 1' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,10 as KPI, 'Rahkaran' as KPI_DETAILS
    ,BALANCE MEASURE
from VW_FIN_FST_STATMENT d
         left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where FST_01_DESC='PC1'
union all
select 'Profit Contribution 2' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,19 as KPI, 'Rahkaran' as KPI_DETAILS
                                       ,BALANCE MEASURE
from VW_FIN_FST_STATMENT d
         left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where FST_01_DESC='PC2'
union all
select 'Profit Contribution 3' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,20 as KPI, 'Rahkaran' as KPI_DETAILS
                                       ,BALANCE MEASURE
from VW_FIN_FST_STATMENT d
         left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where FST_01_DESC='PC3'
union all
select 'EBITDA' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,11 as KPI, 'Rahkaran' as KPI_DETAILS
                        ,BALANCE MEASURE
from VW_FIN_FST_STATMENT d
         left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where FST_01_DESC='EBITDA'
union all
select 'Operating Cash Flow' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,12 as KPI, 'Rahkaran' as KPI_DETAILS
                                     ,BALANCE MEASURE
from VW_FIN_FST_STATMENT d
         left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where FST_01_DESC='Operating Cash Flow'
union all
select 'PBT' kpi_name, to_date(m.LAST_DAY_OF_MONTH,'YYYY/MM/DD','nls_calendar=persian') GDATE
     ,replace(m.LAST_DAY_OF_MONTH,'/','') PDATE
     ,17 as KPI, 'Rahkaran' as KPI_DETAILS
                     ,BALANCE MEASURE
from VW_FIN_FST_STATMENT d
         left join mongodb.dim_month m on m.P_YEARMONTH=d.PYEAR*100+PMONTH
where FST_01_DESC='Net Profit or Loss'
;




INSERT INTO DP_AT_A_GLANCE.STG_AT_GLANCE
select GDATE,PDATE,KPI,KPI_DETAILS,MEASURE
from FINANCE.vw_fin_at_glance d
where not exists(select * from DP_AT_A_GLANCE.STG_AT_GLANCE sg
                 where sg.kpi=d.kpi and sg.PDATE=d.pdate)
;


select * from FINANCE.vw_fin_at_glance d
where pdate=14010431 and kpi=9
;
select * from VW_FIN_FST_STATMENT d
where /*FST_01_CODE='1' and*/ d.PYEAR=1401 and d.pmonth=4
;






