CREATE TABLESPACE TBS_FINANCE DATAFILE
    '/oracle/u01/app/oracle/oradata/dgporclw/tbs_finance00.dbf' SIZE 100M
    AUTOEXTEND ON NEXT 8192 MAXSIZE 20480M
    LOGGING ONLINE PERMANENT BLOCKSIZE 8192
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE DEFAULT
 NOCOMPRESS  SEGMENT SPACE MANAGEMENT AUTO;

create user finance identified by finance default tablespace TBS_FINANCE quota unlimited on TBS_FINANCE;
grant connect,resource,create view to finance;


-- drop table FIN_MOEIN_MAPPING;
create table FIN_MOEIN_MAPPING
(
    ID NUMBER(10) GENERATED BY DEFAULT AS IDENTITY primary key,
    FST varchar2(10),
    FST_02_CODE NUMBER(10),
    FST_02_DESC varchar2(100),
    MOEIN NUMBER(10)
);
create index ix_MOEIN_MAPPING_MOEIN
	on FIN_MOEIN_MAPPING (MOEIN)
;

-- drop table FIN_MOEIN_REPORT_ETL;
create table FIN_MOEIN_REPORT_ETL (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY primary key,
    ETL_DATE date default current_date,
    PYEAR INTEGER,
    PMONTH INTEGER,
    DETAIL_COUNT NUMBER(18),
    DETAIL_Debit_SUM NUMBER(18),
    DETAIL_Credit_SUM NUMBER(18),
    active NUMBER(1) default 1
);

-- drop table FIN_MOEIN_REPORT_DETAIL;
create table FIN_MOEIN_REPORT_DETAIL (
  ID NUMBER(18) GENERATED BY DEFAULT AS IDENTITY primary key,
  F_MOEIN_REPORT_ETL NUMBER(10) not null,
  GLCode       NUMBER(8),
  SLCode       NUMBER(8),
  GNumber       NUMBER(8),
  Sequence     NUMBER(8),
  DailyNumber          NUMBER(8),
  CreationDate         Date,
  LastModificationDate Date,
  VoucherItemID	    NUMBER(18),
  VoucherRef	NUMBER(18),
  BranchRef	    NUMBER(8),
  GLRef	        NUMBER(8),
  SLRef	        NUMBER(8),
  Debit	        NUMBER(18),
  Credit	    NUMBER(18),
  TargetCurrencyRef	    NUMBER(8),
  TargetCurrencyDebit	NUMBER(8),
  TargetCurrencyCredit	NUMBER(8),
  FiscalYearRef	        NUMBER(8),
  GDate	            Date,
  VoucherTypeRef	NUMBER(8),
  State	            NUMBER(8),
  LedgerRef	        NUMBER(8),
  DLLevel4	        NUMBER(18),
  DLLevel5	        NUMBER(18),
  DLLevel6	        NUMBER(18),
  DLLevel7	        NUMBER(18),
  DLLevel8	        NUMBER(18),
  DLLevel9	        NUMBER(18)
);
-- alter table FIN_MOEIN_REPORT_DETAIL add constraint fk_FIN_MOEIN_REPORT_ETL
-- foreign key (F_MOEIN_REPORT_ETL) references FIN_MOEIN_REPORT_ETL (ID);

create index IX_FIN_MOEIN_REPORT_DETAIL_ETL
    on FIN_MOEIN_REPORT_DETAIL (F_MOEIN_REPORT_ETL);

create index IX_FIN_MOEIN_REPORT_DETAIL_SLCODE
    on FIN_MOEIN_REPORT_DETAIL (SLCODE);


update (select etl.ID,etl.DETAIL_COUNT,etl.DETAIL_Credit_SUM,etl.DETAIL_Debit_SUM
            ,detail.F_MOEIN_REPORT_ETL,detail.DETAIL_COUNT2
            ,detail.DETAIL_Debit_SUM2,detail.DETAIL_Credit_SUM2
    from FIN_MOEIN_REPORT_ETL etl
    join (select F_MOEIN_REPORT_ETL,count(*) DETAIL_COUNT2
    ,sum(Debit) DETAIL_Debit_SUM2,sum(Credit) DETAIL_Credit_SUM2
    from FIN_MOEIN_REPORT_DETAIL group by F_MOEIN_REPORT_ETL) detail
    on detail.F_MOEIN_REPORT_ETL=etl.ID
    where etl.id=2)
set
    DETAIL_COUNT =DETAIL_COUNT2,
    DETAIL_Debit_SUM =DETAIL_Debit_SUM2,
    DETAIL_Credit_SUM =DETAIL_Credit_SUM2
where id=2
;
update FIN_MOEIN_REPORT_ETL set active=0 where pyear={year} and pmonth={month} and active=1
;


select * from FIN_MOEIN_MAPPING;
select * from FIN_MOEIN_REPORT_ETL;
select * from FIN_MOEIN_REPORT_DETAIL;
-- truncate table FIN_MOEIN_REPORT_ETL;
-- truncate table FIN_MOEIN_REPORT_DETAIL;


select m.ID,m.FST,m.FST_02_CODE,m.FST_02_DESC,m.MOEIN
     ,sum(d.CREDIT)
     ,sum(d.DEBIT)
     ,d.slcode,e.id etlid
from FIN_MOEIN_MAPPING m
left join FIN_MOEIN_REPORT_DETAIL d on m.MOEIN = d.slcode
left join FIN_MOEIN_REPORT_ETL e on e.ID=d.F_MOEIN_REPORT_ETL
where e.pyear=1400 and e.PMONTH=1 and e.active=1
group by m.ID,m.FST,m.FST_02_CODE,m.FST_02_DESC,m.MOEIN,d.slcode,e.id
;



select m.ID,m.FST,m.FST_02_CODE,m.FST_02_DESC,m.MOEIN
     ,sum(d.CREDIT)
     ,sum(d.DEBIT)
     ,d.slcode,e.id etlid
from FIN_MOEIN_REPORT_DETAIL d
full join FIN_MOEIN_MAPPING m on m.MOEIN = d.slcode
left join FIN_MOEIN_REPORT_ETL e on e.ID=d.F_MOEIN_REPORT_ETL
where e.pyear=1400 and e.PMONTH=1 and e.active=1
group by m.ID,m.FST,m.FST_02_CODE,m.FST_02_DESC,m.MOEIN,d.slcode,e.id
;



create view vw_fin_fst_balance as
select m.FST_02_CODE,m.FST_02_DESC
     ,nvl(sum(d.DEBIT),0)-nvl(sum(d.CREDIT),0) balance
    ,e.pyear,e.pmonth
from FIN_MOEIN_REPORT_DETAIL d
         full join FIN_MOEIN_MAPPING m on m.MOEIN = d.slcode
         left join FIN_MOEIN_REPORT_ETL e on e.ID=d.F_MOEIN_REPORT_ETL
where e.active=1
group by m.FST_02_CODE,m.FST_02_DESC,e.pyear,e.pmonth
;

select FST_02_CODE,FST_02_DESC,PYEAR,PMONTH,BALANCE from vw_fin_fst_balance
;

select * from finance.vw_fin_fst_balance
pivot (sum(balance) for pmonth in (1 فروردین,2 اردیبهشت,3 خرداد,4 تیر,5 مرداد,6 شهریور,7 مهر,8 آبان,9 آذر,10 دی,11 بهمن,12 اسفند))
order by FST_02_CODE
;
CP_MONGODB
;
select TO_CHAR(TO_DATE(7, 'MM','nls_calendar=persian'), 'MONTH','nls_calendar=persian') from dual;
;
;
with fst_balance as
( select to_char(FST_02_CODE) FST_02_CODE, FST_02_DESC,to_char(pyear) pyear,to_char(pmonth) pmonth,balance
,case pmonth
from finance.vw_fin_fst_balance
    order by pmonth)
select * from fst_balance
pivot (sum(balance) for pmonth in (1 فروردین,2 اردیبهشت,3 خرداد,4 تیر,5 مرداد,6 شهریور,7 مهر,8 آبان,9 آذر,10 دی,11 بهمن,12 اسفند))
order by FST_02_CODE
;


select to_char(FST_02_CODE) FST_02_CODE, FST_02_DESC,to_char(pyear) pyear,to_char(pmonth) pmonth,balance
     ,lpad(pmonth,2,'0')||'-'|| case pmonth when 1 then 'فروردین'when 2 then 'اردیبهشت' when 3 then 'خرداد'
        when 4 then 'تیر' when 5 then 'مرداد'when 6 then 'شهریور'
        when 7 then 'مهر' when 8 then 'آبان'when 9 then 'آذر'
        when 10 then 'دی' when 11 then 'بهمن'when 12 then 'اسفند'
        else '(نامشخص)' end pmonthname
from finance.vw_fin_fst_balance
order by lpad(FST_02_CODE,4,0),pmonth
;

